#############################################################################
# Makefile for building drawlines
# Generated by tmake at 10:31, 2001/06/08
#     Project: drawlines
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	cl
CXX	=	cl
CFLAGS	=	-nologo -W3 -MD -O1 -DQT_DLL -DQT_THREAD_SUPPORT -DNO_DEBUG
CXXFLAGS=	-nologo -W3 -MD -O1 -DQT_DLL -DQT_THREAD_SUPPORT -DNO_DEBUG
INCPATH	=	-I"$(QTDIR)\include"
LINK	=	link
LFLAGS	=	/NOLOGO /SUBSYSTEM:windows
LIBS	=	$(QTDIR)\lib\qt-mt230nc.lib $(QTDIR)\lib\qtmain.lib kernel32.lib user32.lib gdi32.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib imm32.lib winmm.lib wsock32.lib
MOC	=	moc
UIC	=	uic

ZIP	=	zip -r -9

####### Files

HEADERS =	
SOURCES =	connect.cpp
OBJECTS =	connect.obj
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	drawlines.exe
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .c

.cpp.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.cxx.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.cc.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.c.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -Fo$@ $<

####### Build rules

all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) /OUT:$(TARGET) @<<
	    $(OBJECTS) $(OBJMOC) $(LIBS)
<<

moc: $(SRCMOC)

tmake: Makefile

Makefile: drawlines.pro
	tmake drawlines.pro -o Makefile

dist:
	$(ZIP) drawlines.zip drawlines.pro $(SOURCES) $(HEADERS) $(DIST) $(INTERFACES)

clean:
	-del connect.obj
	-del $(TARGET)

####### Compile

connect.obj: connect.cpp \
		..\..\include\qwidget.h \
		..\..\include\qwindowdefs.h \
		..\..\include\qobjectdefs.h \
		..\..\include\qglobal.h \
		..\..\include\qfeatures.h \
		..\..\include\qconfig.h \
		..\..\include\qstring.h \
		..\..\include\qcstring.h \
		..\..\include\qarray.h \
		..\..\include\qgarray.h \
		..\..\include\qshared.h \
		..\..\include\qnamespace.h \
		..\..\include\qwindowdefs_win.h \
		..\..\include\qobject.h \
		..\..\include\qevent.h \
		..\..\include\qregion.h \
		..\..\include\qrect.h \
		..\..\include\qsize.h \
		..\..\include\qpoint.h \
		..\..\include\qmime.h \
		..\..\include\qlist.h \
		..\..\include\qglist.h \
		..\..\include\qcollection.h \
		..\..\include\qstringlist.h \
		..\..\include\qvaluelist.h \
		..\..\include\qdatastream.h \
		..\..\include\qiodevice.h \
		..\..\include\qregexp.h \
		..\..\include\qpaintdevice.h \
		..\..\include\qpalette.h \
		..\..\include\qcolor.h \
		..\..\include\qbrush.h \
		..\..\include\qcursor.h \
		..\..\include\qfont.h \
		..\..\include\qfontmetrics.h \
		..\..\include\qfontinfo.h \
		..\..\include\qstyle.h \
		..\..\include\qsizepolicy.h \
		..\..\include\qpainter.h \
		..\..\include\qpen.h \
		..\..\include\qpointarray.h \
		..\..\include\qwmatrix.h \
		..\..\include\qapplication.h \
		..\..\include\qasciidict.h \
		..\..\include\qgdict.h \
		..\..\include\qtranslator.h \
		..\..\include\qintdict.h

